### ISSUE TITLE
do we need a short note on which development flow would be used?

### ISSUE THREAD

**Issue by volodymyrss** [workflowhub-eu/workflowhub-graph#14]
Following today's meeting, as the understanding of the processes is being crystalized, is it useful to note it in a README.md or so? Like, which branches  (develop, main, feature), tags, who creates when and when. 

Especially so that we, as more external contributors, know how to contribute in a useful and non-distruptive way.

Note sure if I should make this issue, feel free to close it if you prefer to do this differently.

**Comment by alexhambley** [comment]
Good idea to make things clearer, I'll work on this today.

**Comment by alexhambley** [comment]
Now addressed by https://github.com/workflowhub-eu/workflowhub-graph/commit/3cbe9a82a8221d703938685bf595ef35f19a9b1f
