### ISSUE TITLE
Some RO Crates raise a ValueError if there are multiple context URLs

### ISSUE THREAD

**Issue by alexhambley** [workflowhub-eu/workflowhub-graph#34]
Crates may have multiple top level context URLs, e.g. 

```
{
  "@context": [
    "https://w3id.org/ro/crate/1.1/context",
    "https://w3id.org/ro/terms/workflow-run"
  ],
...
}
```
These currently raise a ValueError in `cached_url_open.py`. Example workflow ID that causes this error is [1046](https://workflowhub.eu/workflows/1046).

**Comment by alexhambley** [comment]
@volodymyrss - I was wondering if you could take a look at this at some point? Let me know if you need any more details.

**Comment by volodymyrss** [comment]
I could have a look, yes, in the next days. I assign the issue to myself then?

By the way, will we have regular meeting at some point to get updated a bit on the state and plans? It's been a while, I am not sure I am quite up to date.
