### ISSUE TITLE
Investigate the suitability of Ontospy / alternatives

### ISSUE THREAD

**Issue by OliverWoolland** [workflowhub-eu/workflowhub-graph#9]

**Comment by OliverWoolland** [comment]
Is https://github.com/digitalbazaar/pyld a viable alternative to ontospy?

**Comment by stain** [comment]
Jena Riot https://jena.apache.org/documentation/io/#command-line-tools can also do conversion easily.  Docker image in https://hub.docker.com/r/stain/jena or use Java.

There's an in-memory cache in Riot https://github.com/jsonld-java/jsonld-java/blob/master/README.md#controlling-network-traffic but of course that would be cleared for each `riot` command line unless you provided multiple files. 

To override the JSON-LD `@context` cache you can ask it to load context from classpath, see [jarcache.json](https://github.com/jsonld-java/jsonld-java/blob/master/README.md#loading-contexts-from-classpath) however this may need a new `Dockerfile`

**Comment by stain** [comment]
https://rdflib.readthedocs.io/en/stable/ can read JSON-LD in Python and export other formats, you should not need `pyld`

**Comment by stain** [comment]
Decided on rdlib with Volodymyr's JSON-LD caching patch.
